package shidongliang.bwei.com.greendao1130.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import shidongliang.bwei.com.greendao1130.Bean;
import shidongliang.bwei.com.greendao1130.LoginBean;
import shidongliang.bwei.com.greendao1130.NewslistBean;

import shidongliang.bwei.com.greendao1130.dao.BeanDao;
import shidongliang.bwei.com.greendao1130.dao.LoginBeanDao;
import shidongliang.bwei.com.greendao1130.dao.NewslistBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beanDaoConfig;
    private final DaoConfig loginBeanDaoConfig;
    private final DaoConfig newslistBeanDaoConfig;

    private final BeanDao beanDao;
    private final LoginBeanDao loginBeanDao;
    private final NewslistBeanDao newslistBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beanDaoConfig = daoConfigMap.get(BeanDao.class).clone();
        beanDaoConfig.initIdentityScope(type);

        loginBeanDaoConfig = daoConfigMap.get(LoginBeanDao.class).clone();
        loginBeanDaoConfig.initIdentityScope(type);

        newslistBeanDaoConfig = daoConfigMap.get(NewslistBeanDao.class).clone();
        newslistBeanDaoConfig.initIdentityScope(type);

        beanDao = new BeanDao(beanDaoConfig, this);
        loginBeanDao = new LoginBeanDao(loginBeanDaoConfig, this);
        newslistBeanDao = new NewslistBeanDao(newslistBeanDaoConfig, this);

        registerDao(Bean.class, beanDao);
        registerDao(LoginBean.class, loginBeanDao);
        registerDao(NewslistBean.class, newslistBeanDao);
    }
    
    public void clear() {
        beanDaoConfig.clearIdentityScope();
        loginBeanDaoConfig.clearIdentityScope();
        newslistBeanDaoConfig.clearIdentityScope();
    }

    public BeanDao getBeanDao() {
        return beanDao;
    }

    public LoginBeanDao getLoginBeanDao() {
        return loginBeanDao;
    }

    public NewslistBeanDao getNewslistBeanDao() {
        return newslistBeanDao;
    }

}
